xx

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -32,35 +32,35 @@ jobs:
 
       - name: Install Dependencies (Windows)
         if: runner.os == 'Windows'
-        shell: bash
+        # shell: bash
         run: |
           choco install --no-progress MozillaBuild
-          find "C:\mozilla-build"
+          # find "C:\mozilla-build"
 
-      # - name: Install Rust
-      #   uses: actions-rust-lang/setup-rust-toolchain@v1
-      #   with:
-      #     toolchain: ${{ matrix.rust-toolchain }}
-      #     components: rustfmt, clippy
-      #     cache: false # enabling the cache leads to spurious failures
+      - name: Install Rust
+        uses: actions-rust-lang/setup-rust-toolchain@v1
+        with:
+          toolchain: ${{ matrix.rust-toolchain }}
+          components: rustfmt, clippy
+          cache: false # enabling the cache leads to spurious failures
 
-      # - name: Checkout
-      #   uses: actions/checkout@v4
+      - name: Checkout
+        uses: actions/checkout@v4
 
-      # - name: Build
-      #   shell: bash
-      #   run: cargo +${{ matrix.rust-toolchain }} build -v --tests
+      - name: Build
+        shell: bash
+        run: cargo +${{ matrix.rust-toolchain }} build -v --tests
 
-      # - name: Run Tests
-      #   run: cargo +${{ matrix.rust-toolchain }} test -v
-      #   env:
-      #      RUST_BACKTRACE: 1
-      #      RUST_LOG: neqo=debug
+      - name: Run Tests
+        run: cargo +${{ matrix.rust-toolchain }} test -v
+        env:
+           RUST_BACKTRACE: 1
+           RUST_LOG: neqo=debug
 
-      # - name: Check formatting
-      #   run: cargo +${{ matrix.rust-toolchain }} fmt --all -- --check
-      #   if: ${{ success() || failure() }}
+      - name: Check formatting
+        run: cargo +${{ matrix.rust-toolchain }} fmt --all -- --check
+        if: ${{ success() || failure() }}
 
-      # - name: Clippy
-      #   run: cargo +${{ matrix.rust-toolchain }} clippy -v --tests -- -D warnings
-      #   if: ${{ success() || failure() }}
+      - name: Clippy
+        run: cargo +${{ matrix.rust-toolchain }} clippy -v --tests -- -D warnings
+        if: ${{ success() || failure() }}
